apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  labels:
    app: nodejs-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server-container
        image: avatarbg111/vct_web_app:v2
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 5000
  selector:
    app: nodejs-server